=head1 NAME
 
 Transactions - Contains the response from a transactions request to the Moms API
 

=cut

=head1 SYNOPSIS
 
=begin html
 
 <b>use</b> Transactions;</br>
 <b>new Transactions</b>($xmlDoc); #$xmlDoc is an xml file
 
=end html
 

=cut

=head1 DESCRIPTION
 
=begin html
 
 The Transactions object contains the response from a <A HREF="mercury.html#transactions">transactions</A> request to the Moms API.
 
=end html
 

=cut

=head1 CONSTRUCTOR
 
=head2 Transactions
 
=over 4

=item Transactions($xmlDoc)
 
 Creates a new Transactions response object.

=begin html
 
 <b>Paramters</b>: $xmlDoc: XML document that is returned by all the requests.
 
=end html
 
=back
 

=cut

=head1 FUNCTIONS
 
=head2 getCampaignsIdList
 
=over 4

=item getCampaignsIdList()

=begin html
 
 <b>Returns</b> the list of all the campaigns ID.
 
=end html
 
=back
 

=cut

=head2 getCampaignNames
 
=over 4
 
=item getCampaignNames($campaignId)
 
=begin html
 
 <b>Returns</b> the names for the specified campaign ID (a campaign can have more than one name).

=end html
 
=back
  

=cut

=head2 getTransactionsIdList
 
=over 4
 
=item getTransactionsIdList()
 
=begin html
 
 <b>Returns</b> the list of all the transactions ID.
 
=end html
 
=back
  

=cut

=head2 getTransactionsIdListFrom
 
=over 4
 
=item getTransactionsIdListFrom($campaignId)
 
=begin html
 
 <b>Returns</b> the list of all the transactions ID for the specified campaign ID.
 
=end html
 
=back
 

=cut

=head2 getValue
 
=over 4
 
=item getValue($campaignId,$transactionId,$key)
 
=begin html
 
 <b>Returns</b> the value for the specified key.
 
=end html
  
=back
 

=cut

=head2 getHash
 
=over 4
 
=item getHash($campaignId,$transactionId)

=begin html
 
 <b>Returns</b> the hash corresponding to the specified campaign ID and transaction ID. Null if the campaign ID or the transaction ID does not exist.

=end html
 
=back
  

=cut

=head2 getDatestamp
 
=over 4
 
=item getDatestamp($campaignId,$transactionId)
 
=begin html
 
 <b>Returns</b> the datestamp corresponding to the specified campaign ID and transaction ID. Null if the campaign ID or the transaction ID does not exist.
 
=end html
 
=back
 

=cut

=head2 getFromNumber
 
=over 4
 
=item getFromNumber($campaignId,$transactionId)
 
=begin html
 
 <b>Returns</b> the sender's number corresponding to the specified campaign ID and transaction ID. Null if the campaign ID or the transaction ID does not exist.
 
=end html
 
=back
  

=cut

=head2 getFromName
 
=over 4
 
=item getFromName($campaignId,$transactionId)
 
=begin html
 
 <b>Returns</b> the sender's name corresponding to the specified campaign ID and transaction ID. Null if the campaign ID or the transaction ID does not exist.
 
=end html
 
=back
 

=cut

=head2 getToNumber
 
=over 4

=item getToNumber($campaignId,$transactionId)
 
=begin html
 
 <b>Returns</b> the receiver's number corresponding to the specified campaign ID and transaction ID. Null if the campaign ID or the transaction ID does not exist.
 
=end html
 
=back
 

=cut

=head2 getToName
 
=over 4
 
=item getToName($campaignId,$transactionId) 

=begin html
 
 <b>Returns</b> the receiver's name corresponding to the specified campaign ID and transaction ID. Null if the campaign ID or the transaction ID does not exist.
 
=end html
 
=back
  

=cut

=head2 printElts
 
=over 4
 
=item printElts()
 
=begin html
 
 Prints each campaign with its informations.
 
=end html
 
=back
  

=cut

=head1 AUTHOR
 
=begin html
 
 Anais Brossas for Mogreet (<A HREF="http://www.mogreet.com">www.mogreet.com</A>)</br>
 Date: Tuesday, October 04, 2011 
 
=end html
 

=cut

